### ISSUE TITLE
Feature request: Add errors info

### ISSUE THREAD

**Issue by rubasace** [onedr0p/radarr-exporter#3]
It would be super cool to also have metrics for some errors, for being able to alert on any incidence. I can think of 2 main things:

1. When it downloads but cannot import for some reason)
2. Any issue with clients or Indexers (not sure if this one is already part of the status)

**Comment by onedr0p** [comment]
Number 1: I like this suggestion. I don't think it would be too hard to add.

Number 2: I believe the `health_issues` metric should return that info, it shows the type of error.

```go
	// Health - Amount of health issues by type
	Health = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name:      "health_issues",
			Namespace: "radarr",
			Help:      "Amount of health issues in Radarr",
		},
		[]string{"hostname", "type"},
	)
```

**Comment by onedr0p** [comment]
I am trying to think of how to accomplish your first request. As of right now there is a `radarr_queue_total` metric that returns all items in the queue.

I think if we add a field to the metric, called `status` and then group them it would work.

```
# Total items in queue, regardless of status
radarr_queue_total{hostname="http://localhost:7878"} 9
# Total items in queue with warning status
radarr_queue_total{hostname="http://localhost:7878", status="warning"} 9
# Total items in queue with error status
radarr_queue_total{hostname="http://localhost:7878", status="error"} 0
```

Does that fit your use-case?

Edit:

I am unsure if I can retrieve the errored ones, because the radarr API only has TrackedDownloadStatus of Ok and Warning:

https://github.com/Radarr/Radarr/blob/aphrodite/src/NzbDrone.Core/Download/TrackedDownloads/TrackedDownload.cs#L43

**Comment by onedr0p** [comment]
I think I'll be able to grab the TrackedDownloadState from the API once this PR gets merged: https://github.com/Radarr/Radarr/pull/4257

```
public enum TrackedDownloadState
{
        Downloading,
        ImportPending,
        Importing,
        Imported,
        FailedPending,
        Failed,
        Ignored
}
```

For now, all I can grab is

```
# Total items in queue with Ok status
radarr_queue_total{hostname="http://localhost:7878", status="Ok"} 0
# Total items in queue with Warning status
radarr_queue_total{hostname="http://localhost:7878", status="Warning"} 9
```

**Comment by onedr0p** [comment]
Current work is done in v1.2.0, opened issue https://github.com/onedr0p/radarr-exporter/issues/8 to track the upcoming Radarr changes.
